name: Build bfsgit for Windows and Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Publish Windows binary
      - name: Publish for Windows
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish

      # Publish Linux binary
      - name: Publish for Linux
        run: dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -o ./publish

      # Rename Linux binary for clarity
      - name: Rename Linux binary
        run: mv ./publish/bfsgit ./publish/bfsgit-linux

      # Upload both binaries as a single artifact
      - name: Upload both binaries as single artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: |
            ./publish/bfsgit.exe
            ./publish/bfsgit-linux

      # Create GitHub Release and attach both binaries
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: autobuild-${{ github.run_number }}
          name: bfsgit autobuild ${{ github.run_number }}
          body: |
            Automatic build for Windows and Linux.
          files: |
            ./publish/bfsgit.exe
            ./publish/bfsgit-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
